# This is a basic workflow to help you get started with Actions

name: Script Runner

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron:  '*/15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        FTP_SERVER    :  ${{ secrets.FTP_SERVER }}
        FTP_SUBDIR    :  ${{ secrets.FTP_SUBDIR }}
        FTP_USER      :  ${{ secrets.FTP_USER }}
        FTP_PASSWORD  :  ${{ secrets.FTP_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sh ./organize.sh
  refresh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        DASHBOARD_URL     :  ${{ secrets.DASHBOARD_URL }}
        PASSFIELD         :  ${{ secrets.PASSFIELD }}
        REFRESH_URL       :  ${{ secrets.REFRESH_URL }}
        USERFIELD         :  ${{ secrets.USERFIELD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sh ./curl.sh